import Nav from '@/components/common/nav';
import Head from 'next/head';

const ArticleIndex = () => {
  return (
    <div>
      <Head>
        <title>乐问</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      article index page
    </div>
  );
};
export default ArticleIndex;
