import Nav from '@/components/common/nav';
import { Button } from 'antd';
import classNames from 'classnames';
import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';
import style from './index.module.css';
import { useEffect, useState } from 'react';
import { ArticleItem } from '@/config/types/article';

const QueIndex = () => {
  const [newestList, setNewestList] = useState<ArticleItem[]>([]);

  useEffect(() => {
    axios('/api/q').then(({ data }) => {
      if (data.code === 0) {
        setNewestList(data.data);
      }
    });
  }, []);

  return (
    <div className="container question-page">
      <Head>
        <title>乐问</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className={classNames('content', style.content)}>
        <div className={style.main}>
          <div className="carefully-chosen">
            <h2>精选</h2>
            <ul>
              <li className={style['carefully-chosen-li']}>
                <Link href="https://www.xiabingbao.com" target="_blank">
                  erkjgelrjgelrj乐然关键路径
                </Link>
                <p className="date">20222/11/20 13:23</p>
              </li>
              <li className={style['carefully-chosen-li']}>
                <Link href="https://www.xiabingbao.com" target="_blank">
                  erkjgelrjgelrj乐然关键路径
                </Link>
                <p className="date">20222/11/20 13:23</p>
              </li>
              <li className={style['carefully-chosen-li']}>
                <Link href="https://www.xiabingbao.com" target="_blank">
                  erkjgelrjgelrj乐然关键路径
                </Link>
                <p className="date">20222/11/20 13:23</p>
              </li>
              <li className={style['carefully-chosen-li']}>
                <Link href="https://www.xiabingbao.com" target="_blank">
                  erkjgelrjgelrj乐然关键路径
                </Link>
                <p className="date">20222/11/20 13:23</p>
              </li>
            </ul>
          </div>
          <div className="newest-list">
            {newestList.map((item) => (
              <div className="item" key={item.id}>
                <h3>
                  <Link href={item.url}>{item.title}</Link>
                </h3>
                <div className="info">
                  <span className="view">浏览 {item.view}</span>
                  <span className="view">回答 {item.reply}</span>
                  <span className="time" style={{ float: 'right' }}>
                    {item.pub_time}
                  </span>
                </div>
                <div className="desc">{item.desc}</div>
              </div>
            ))}
          </div>
        </div>
        <div className={style.right}>
          <Button>提出问题</Button>
          <div className="carefully-chosen">
            <h2>热榜</h2>
            <ul>
              <li className={style['carefully-chosen-li']}>
                <Link href="https://www.xiabingbao.com" target="_blank">
                  erkjgelrjgelrj乐然关键路径
                </Link>
                <p className="date">20222/11/20 13:23</p>
              </li>
              <li className={style['carefully-chosen-li']}>
                <Link href="https://www.xiabingbao.com" target="_blank">
                  erkjgelrjgelrj乐然关键路径
                </Link>
                <p className="date">20222/11/20 13:23</p>
              </li>
              <li className={style['carefully-chosen-li']}>
                <Link href="https://www.xiabingbao.com" target="_blank">
                  erkjgelrjgelrj乐然关键路径
                </Link>
                <p className="date">20222/11/20 13:23</p>
              </li>
              <li className={style['carefully-chosen-li']}>
                <Link href="https://www.xiabingbao.com" target="_blank">
                  erkjgelrjgelrj乐然关键路径
                </Link>
                <p className="date">20222/11/20 13:23</p>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
export default QueIndex;
